title = "Rail Fence Cipher"
blurb = "Implement encoding and decoding for the rail fence cipher."
source = "Wikipedia"
source_url = "https://en.wikipedia.org/wiki/Transposition_cipher#Rail_Fence_cipher"
