title = "Raindrops"
blurb = "Convert a number into its corresponding raindrop sounds - Pling, Plang and Plong."
source = "A variation on FizzBuzz, a famous technical interview question that is intended to weed out potential candidates. That question is itself derived from Fizz Buzz, a popular children's game for teaching division."
source_url = "https://en.wikipedia.org/wiki/Fizz_buzz"
deep_dive_youtube_id = "mwe-9RIV39Y"
