title = "Book Store"
blurb = "To try and encourage more sales of different books from a popular 5 book series, a bookshop has decided to offer discounts of multiple-book purchases."
source = "Inspired by the harry potter kata from Cyber-Dojo."
source_url = "https://cyber-dojo.org"
