title = "Leap"
blurb = "Determine whether a given year is a leap year, without using built-in functionality."
source = "CodeRanch Cattle Drive, Assignment 3"
source_url = "https://coderanch.com/t/718816/Leap"
deep_dive_youtube_id = "Fj5m16is5hI"
