name: CI

on:
  pull_request:

jobs:
  required-files:
    name: All required files are present
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: All required files are present
        run: bin/check_required_files_present

  immutability:
    name: No test has been mutated
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          path: "new"

      # Pull Requests
      - name: Checkout the target branch
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          ref: "${{ github.base_ref }}"
          path: "old"

      - name: Check that no test has been mutated
        run: |
          for oldf in old/exercises/*/canonical-data.json; do
            newf=${oldf//old/new}
            ./new/bin/check-immutability.py "$oldf" "$newf"
          done

  schema-validation:
    name: Schema validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: "12"

      # https://github.com/actions/cache/blob/main/examples.md#node---yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Verify that canonical-data.json files adhere to their json schema
        run: yarn test

      - name: Verify that all UUIDs are indeed unique
        run: |
          duplicate_uuids=$(cat exercises/*/canonical-data.json |
              jq -r '.. |."uuid"? | select(. != null)' |          # select all UUIDs
              sort | uniq -d)                                     # check for repeated UUIDs
          if [ -n "$duplicate_uuids" ]; then
              echo "The following UUIDs are not unique:"
              echo "$duplicate_uuids"
              exit 1
          fi

      - name: Verify that reimplements-values refer to existing UUID
        run: |
          fail=0

          for f in exercises/*/canonical-data.json; do
              # Search for reimplemented test cases
              reimplements=$(jq -r '.. |."reimplements"? | select(. != null)' "$f")

              # Abort early if the exercise doesn't have reimplemented test cases
              [[ -e $reimplements ]] && continue

              uuids=$(jq -r '.. |."uuid"? | select(. != null)' "$f")
              for reimplemented_uuid in $reimplements; do
                  if [[ $uuids != *"$reimplemented_uuid"* ]]; then
                      echo "$f: reimplemented value refers to a test case with UUID $reimplemented_uuid, but the file does not contain any test cases with that UUID."
                      fail=1
                  fi
              done
          done

          exit "$fail"

      - name: Verify that all scenarios are defined in the schema
        run: |
          canonical_data_schema_file="canonical-data.schema.json"
          scenarios_file="SCENARIOS.txt"

          fail=0

          while read -r scenario; do
              jq -e ".definitions.scenario.enum | index(\"$scenario\")" $canonical_data_schema_file > /dev/null

              if [ $? -eq 1 ]; then
                  echo "$canonical_data_schema_file: scenario '$scenario' is missing from the '.definitions.scenario.enum' field."
                  fail=1
              fi
          done < $scenarios_file

          exit "$fail"

      - name: Verify that all keys are in the correct order
        run: ./bin/check_key_order.rb

  markdown-lint:
    name: Lint markdown files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - uses: DavidAnson/markdownlint-cli2-action@e3969ef4ed874458f4b66d4631f78fff7717012c
        with:
          globs: |
            **/*.md

  json-lint:
    name: Lint json files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Verify that json files are formatted correctly
        run: |
          yarn format-json && ruby bin/format-array.rb
          if ! git diff --quiet --exit-code; then
            echo "please format the files with prettier and bin/format-array.rb, or apply the following changes:"
            git diff
            exit 1
          fi
