name: CI

on:
  pull_request:
  push: 
    branches: 
      - master

jobs:
  required-files:
    name: All required files are present
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: All required files are present
        run: bin/check_required_files_present
  
  immutability:
    name: No test has been mutated
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'new'

      # Pull Requests
      - name: Checkout the target branch (PRs)
        uses: actions/checkout@v2
        if: github.event_name == 'pull_request'
        with:
          ref: '${{ github.base_ref }}'
          path: 'old'
      
      # Pushes
      - name: Checkout the previous commit (Pushes)
        uses: actions/checkout@v2
        if: github.event_name == 'push'
        with:
          ref: '${{ github.sha }}~'
          path: 'old'
      
      - name: Check that no test has been mutated
        run: |
          for oldf in exercises/*/canonical-data.json; do
            newf=${oldf//old/new}
            ./new/bin/check-immutability.py "$oldf" "$newf"
          done

  schema-validation:
    name: Schema validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      # https://github.com/actions/cache/blob/master/examples.md#node---yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Verify that canonical-data.json files adhere to canonical-schema.json
        run: yarn test
      
      - name: Verify that all UUIDs are indeed unique
        run: |
          duplicate_uuids=$(cat exercises/*/canonical-data.json |
              grep '"uuid":' |                                    # select UUID line
              sed -E 's/.*"([^"]+)".*/\1/' |                      # extract JSON value
              sort | uniq -d)                                     # check for repeated UUIDs
          if [ -n "$duplicate_uuids" ]; then
              echo "The following UUIDs are not unique:"
              echo "$duplicate_uuids"
              exit 1
          fi
